#!/usr/bin/env node
/* =====================================================================
   Moonlit Shrine · theme generator
   Input : 12 themes × 4 parameters
   Output: public/moonlit-shrine-themes.css  (static [data-color-theme] blocks)
           design/theme-contrast-audit.md    (measured WCAG ratios per theme)
   Run   : node scripts/generate-themes.js   (from anywhere — paths are
           resolved relative to this file, not the working directory)
   Adding a theme is four numbers in the array below, not nineteen hex
   values — see design/moonlit-shrine-design-system.md §3.2 and §15.
   ===================================================================== */
const fs = require('fs');
const path = require('path');
const CSS_OUT = path.join(__dirname, '..', 'public', 'moonlit-shrine-themes.css');
const AUDIT_OUT = path.join(__dirname, '..', 'design', 'theme-contrast-audit.md');
const THEME_BUILDER_URL = 'file:///' + path.join(__dirname, '..', 'public', 'js', 'themeBuilder.js').replace(/\\/g, '/');

const themes = [
  // v3 Phase 4 (decision D2): the twelve curated themes. The 41 retired ones and
  // the curated theme each maps to are listed in public/js/themes.js (RETIRED_THEMES).
  {key:"moonlit-shrine",name:"Moonlit Shrine",fam:"ash",base:[222,18],accent:[356,64,54],glow:[214,42,78],deco:[4,48,54]},
  {key:"bloom",name:"Bloom",fam:"sakura",base:[318,16],accent:[338,58,60],glow:[320,38,80],deco:[344,48,60]},
  {key:"solar",name:"Solar",fam:"lantern",base:[32,18],accent:[38,64,58],glow:[44,50,80],deco:[26,52,54]},
  {key:"parchment",name:"Parchment",fam:"lantern",base:[40,20],accent:[24,50,42],glow:[40,34,58],deco:[18,40,48],light:true},
  {key:"jade",name:"Jade",fam:"jade",base:[168,18],accent:[166,50,54],glow:[176,36,74],deco:[152,42,52]},
  {key:"frost",name:"Frost",fam:"frost",base:[204,18],accent:[196,52,66],glow:[200,44,84],deco:[188,40,62]},
  {key:"amethyst",name:"Amethyst",fam:"iris",base:[268,20],accent:[272,50,64],glow:[264,38,80],deco:[280,42,60]},
  {key:"ember",name:"Ember",fam:"ember",base:[16,16],accent:[18,64,56],glow:[30,46,76],deco:[10,54,52]},
  {key:"obsidian",name:"Obsidian",fam:"void",base:[240,4],accent:[0,0,86],glow:[240,8,88],deco:[240,6,60]},
  {key:"cobalt",name:"Cobalt",fam:"void",base:[224,26],accent:[220,58,58],glow:[224,44,78],deco:[212,46,56]},
  {key:"daybreak",name:"Daybreak",fam:"void",base:[214,10],accent:[220,44,46],glow:[214,26,64],deco:[204,32,52],light:true},
  {key:"rosequartz",name:"Rose Quartz",fam:"sakura",base:[340,10],accent:[345,44,68],glow:[335,30,84],deco:[350,36,62],light:true}
];

/* ---------- colour maths ----------
   Extracted to public/js/themeBuilder.js (P6.1) so the runtime custom-theme
   builder can call the exact same derivation a user's own accent gets — see
   that module's header comment. Imported here via dynamic import() since
   this script is CommonJS and themeBuilder.js is a browser-loadable ESM
   module. */
async function main() {
  const { buildPalette, css, cssA, hex } = await import(THEME_BUILDER_URL);
  const out = themes.map(buildPalette);

  /* ---------- emit CSS ---------- */
  const header = `/* =====================================================================
   Moonlit Shrine · ${out.length} colour themes
   Generated by scripts/generate-themes.js — do not edit by hand.
   Every theme is derived from four parameters (base, accent, glow, deco)
   and every text colour is verified against its own background:
     --text  >= 12:1    --dim >= 7:1     --faint >= 4.6:1
     --accent-lit >= 4.6:1 on --bg
     --accent-contrast is the text colour that sits on an --accent fill
   Default theme: moonlit-shrine
   ===================================================================== */\n\n`;

  const blocks = out.map(t => {
    const c = t.colours, s = t.surf;
    return `[data-color-theme="${t.key}"] {           /* ${t.name} · ${t.fam}${t.light ? ' · light' : ''} */
  --bg: ${css(s.bg)};
  --bg-deep: ${css(s.bgDeep)};
  --bg-elevated: ${css(s.elevated)};
  --card: ${css(s.card)};
  --card-hover: ${css(s.cardHover)};
  --line: ${css(s.line)};
  --line-lit: ${css(s.lineLit)};
  --text: ${css(c.text)};
  --dim: ${css(c.dim)};
  --faint: ${css(c.faint)};
  --accent: ${css(c.accent)};
  --accent-lit: ${css(c.accentLit)};
  --accent-fill: ${css(c.accentFill)};
  --accent-soft: ${cssA(c.accent, .12)};
  --accent-deep: ${css(c.accentDeep)};
  --accent-contrast: ${css(c.accentContrast)};
  --support: ${css(c.support)};
  --positive: ${css(c.positive)};
  --warning: ${css(c.warning)};
  --glow: ${css(c.glow)};
  --deco: ${css(c.deco)};
  --cover-filter: ${t.light ? 'saturate(.8) brightness(.96) contrast(1.02)' : 'saturate(.66) brightness(.9) contrast(1.05)'};
  --cover-filter-hover: ${t.light ? 'saturate(1) brightness(1) contrast(1)' : 'saturate(.96) brightness(1) contrast(1.03)'};
  color-scheme: ${t.light ? 'light' : 'dark'};
}`;
  }).join('\n\n');

  fs.writeFileSync(CSS_OUT, header + blocks + '\n');

  /* ---------- emit audit ---------- */
  const fails = [];
  const rows = out.map(t => {
    const a = t.audit;
    const bad = [];
    if (a.text < 12) bad.push('text');
    if (a.dim < 7) bad.push('dim');
    if (a.faint < 4.5) bad.push('faint');
    if (a.accentLit < 4.5) bad.push('accent-lit');
    if (a.accentFill < 4.5) bad.push('accent fill');
    if (a.cardText < 4.5) bad.push('text on card');
    if (bad.length) fails.push(`${t.key}: ${bad.join(', ')}`);
    return `| ${t.name} | \`${t.key}\` | ${t.fam}${t.light ? ' · light' : ''} | ${hex(t.colours.accent)} | ${a.text.toFixed(1)} | ${a.dim.toFixed(1)} | ${a.faint.toFixed(1)} | ${a.accentLit.toFixed(1)} | ${a.accentFill.toFixed(1)} | ${bad.length ? '⚠ ' + bad.join(', ') : 'pass'} |`;
  });

  const md = `# Theme contrast audit

Generated by \`scripts/generate-themes.js\`.
${out.length} themes. All ratios are measured, not estimated.

Thresholds: \`--text\` ≥ 12:1 · \`--dim\` ≥ 7:1 · \`--faint\` ≥ 4.5:1 · \`--accent-lit\` ≥ 4.5:1 on \`--bg\` · text on an \`--accent\` fill ≥ 4.5:1.

| Theme | Key | Family | Accent | text | dim | faint | accent-lit | on accent | Result |
|---|---|---|---|---|---|---|---|---|---|
${rows.join('\n')}

## Summary

- Themes: **${out.length}** (${out.filter(t => t.light).length} light, ${out.filter(t => !t.light).length} dark)
- Lowest \`--text\`: **${Math.min(...out.map(t => t.audit.text)).toFixed(1)}:1**
- Lowest \`--dim\`: **${Math.min(...out.map(t => t.audit.dim)).toFixed(1)}:1**
- Lowest \`--faint\`: **${Math.min(...out.map(t => t.audit.faint)).toFixed(1)}:1**
- Lowest \`--accent-lit\`: **${Math.min(...out.map(t => t.audit.accentLit)).toFixed(1)}:1**
- Lowest text-on-accent-fill: **${Math.min(...out.map(t => t.audit.accentFill)).toFixed(1)}:1**
- Themes needing dark text on the accent fill: ${out.filter(t => t.colours.accentContrast[2] < 50).map(t => '`' + t.key + '`').join(', ') || 'none'}
- Failures: ${fails.length ? '\n  - ' + fails.join('\n  - ') : '**none**'}
`;
  fs.writeFileSync(AUDIT_OUT, md);

  console.log(`themes: ${out.length}`);
  console.log(`lowest text ${Math.min(...out.map(t => t.audit.text)).toFixed(2)} | dim ${Math.min(...out.map(t => t.audit.dim)).toFixed(2)} | faint ${Math.min(...out.map(t => t.audit.faint)).toFixed(2)} | accent-lit ${Math.min(...out.map(t => t.audit.accentLit)).toFixed(2)} | on-accent ${Math.min(...out.map(t => t.audit.accentFill)).toFixed(2)}`);
  console.log(`dark text on accent: ${out.filter(t => t.colours.accentContrast[2] < 50).map(t => t.key).join(', ') || 'none'}`);
  console.log(fails.length ? 'FAILURES:\n' + fails.join('\n') : 'no failures');
}

main();
