// Split from tests/run-all.js in v3 Phase 7: the fontManifest.js tests, unchanged
// apart from running under node:test (one top-level test each).
import nodeTest from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

// Paths and require() resolve from tests/, as they did in run-all.js.
const __dirname = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(path.join(__dirname, 'index.js'));
const FIXTURES_DIR = path.join(__dirname, 'fixtures');
const test = (name, fn) => nodeTest(name, fn);
function readFixture(name) {
  return JSON.parse(fs.readFileSync(path.join(FIXTURES_DIR, name), 'utf8'));
}
void assert; void os; void readFixture;

// Shared with other sections in run-all.js.
const { FONT_CATALOG } = await import('file:///' + path.join(__dirname, '..', 'public', 'js', 'fonts.js').replace(/\\/g, '/'));

// -------------------------------------------------------------------------
// public/js/fontManifest.js (P3.1) — GENERATED by
// scripts/generate-font-manifest.js from the real files in public/fonts/.
// Pure data, loaded via dynamic import(). This test proves the generated
// file's shape matches fonts.js's catalog exactly (every id present, no
// extras) and spot-checks facts a hand-written manifest could get wrong.
// -------------------------------------------------------------------------
const fontManifestUrl = 'file:///' + path.join(__dirname, '..', 'public', 'js', 'fontManifest.js').replace(/\\/g, '/');
const { FONT_MANIFEST } = await import(fontManifestUrl);

await test('FONT_MANIFEST has exactly one entry per FONT_CATALOG id, no missing, no extra', () => {
  const catalogIds = new Set(FONT_CATALOG.map((f) => f.id));
  const manifestIds = new Set(Object.keys(FONT_MANIFEST));
  assert.deepEqual([...manifestIds].sort(), [...catalogIds].sort());
});

await test('each manifest entry declares either weights or variableAxes, never both, except the fileless system-default', () => {
  for (const [id, data] of Object.entries(FONT_MANIFEST)) {
    if (id === 'system-default') {
      assert.equal(data.weights, null);
      assert.equal(data.variableAxes, null);
      continue;
    }
    const hasWeights = Array.isArray(data.weights);
    const hasAxes = data.variableAxes !== null && typeof data.variableAxes === 'object';
    assert.notEqual(hasWeights, hasAxes, `${id} should declare exactly one of weights/variableAxes`);
  }
});

await test('Noto Sans JP is the only manifest entry with real Japanese glyph coverage', () => {
  for (const [id, data] of Object.entries(FONT_MANIFEST)) {
    assert.equal(data.jpCoverage, id === 'noto-sans-jp', `${id}'s jpCoverage should be ${id === 'noto-sans-jp'}`);
  }
});

await test('the variable families report a real, non-degenerate weight range', () => {
  for (const id of ['inter', 'dm-sans', 'nunito', 'space-grotesk', 'jetbrains-mono']) {
    const [min, max] = FONT_MANIFEST[id].variableAxes.wght;
    assert.ok(min < max, `${id}'s variable weight range should span more than one value`);
  }
});
